--3.1 (sin terminar)
--mas actualizado
create materialized view V_SOCIOS
build immediate
refresh start with (sysdate) next (trunc(sysdate)+1) + 22/24
as select S.ID_SOCIO Id_socio, S.CEDULA Cedula, S.NOMBRE||' '||S.APELLIDO as "Nombre y Apellido", sum(CA.SALDO_DISPONIBLE) Disponible, 
SUM(CASE CP.ESTADO WHEN 'A' THEN CC.MONTO_CUOTA ELSE 0 end) Deuda, 
SUM(CASE SC.TIPO_OBLIGACION WHEN 'A' THEN SC.Total_A_Abonar ELSE 0 end) Aporte
from SOC_SOCIO S join AHO_CUENTA_AHORRO CA
ON S.ID_SOCIO = CA.ID_SOCIO
JOIN CRE_SOLICITUD_PRESTAMOS CSP ON
S.ID_SOCIO = CSP.SOCIO_DEUDOR
JOIN CRE_PRESTAMOS CP ON
CSP.ID_SOL_CRED = CP.ID_SOL_CRED
JOIN CRE_CUOTAS CC ON
CP.NRO_PRESTAMO = CC.NRO_PRESTAMO
JOIN SOC_OBLIGACIONES SC ON
SC.ID_SOCIO = S.ID_SOCIO
group by S.id_socio, S.cedula, S.NOMBRE||' '||S.APELLIDO;


----MONTO CUOTAS ---NO PAGADAS---?????
fecha vencimiento < sysdate?

disponible, deuda, aportes tiene sumatoria

--3.2 (borrador)
create materialized view V_PRESTAMOS
build immediate
refresh start with (sysdate) next (trunc(sysdate)+1/24)
SELECT DISTINCT S.NOMBRE||' '||S.APELLIDO as "Nombre y Apellido", SUM(DECODE(AC.INGRESO_GASTO, 'I',AD.IMPORTE,0) - DECODE(AC.INGRESO_GASTO,'G',AD.IMPORTE,0)) AS "Ingresos",
SUM(DISTINCT AI.VALOR_FISCAL) as "Valor Activos", sum(DISTINCT VS.DISPONIBLE) Disponible,  CP.NRO_PRESTAMO as "Nro Prestamo",
CP.MONTO_PRESTAMO as "Monto Prestamo", CP.FECHA_DESEMBOLSO as "Fecha Desembolso", MAX(CC.FECHA_PAGO) as "Ultima fecha de pago",
SUM(DISTINCT(CASE WHEN CC.FECHA_PAGO IS NOT NULL THEN CC.MONTO_CUOTA - CC.INTERES_MORATORIO ELSE 0 END)) "Monto Cuotas Pagadas",
SUM(DISTINCT(CASE WHEN CC.FECHA_PAGO IS NULL THEN CC.MONTO_CUOTA ELSE 0 END)) AS "Monto cuotas pendientes"
FROM SOC_SOCIO S
JOIN ALD_DECLARACION_JURADA ADJ
ON ADJ.ID_SOCIO = S.ID_SOCIO
JOIN ALD_DETALLE_DECLARACION AD
ON AD.ID_DECLARACION = ADJ.ID_DECLARACION
JOIN ALD_CONCEPTOS AC
ON AC.ID_CONCEPTO = AD.ID_CONCEPTO
JOIN ALD_INMUEBLES AI
ON AI.ID_SOCIO = S.ID_SOCIO
JOIN V_SOCIOS VS
ON VS.Id_socio = S.ID_SOCIO
JOIN AHO_CUENTA_AHORRO CA
ON S.ID_SOCIO = CA.ID_SOCIO
JOIN CRE_SOLICITUD_PRESTAMOS CSP
ON S.ID_SOCIO = CSP.SOCIO_DEUDOR
JOIN CRE_PRESTAMOS CP
ON CP.ID_SOL_CRED=CSP.ID_SOL_CRED
JOIN CRE_CUOTAS CC
ON CC.NRO_PRESTAMO = CP.NRO_PRESTAMO
WHERE CP.ESTADO='A'
group by S.id_socio, S.cedula, S.NOMBRE||' '||S.APELLIDO, CP.NRO_PRESTAMO, CP.MONTO_PRESTAMO, CP.FECHA_DESEMBOLSO;